site_name: robustar-docs
theme:
  name: material
nav:
  - Home: index.md
  - Influence: influence.md
  - Annotation: annotation.md
  - Task Center: task.md
  - Auto Annotation: auto_annotation.md
  - View model prediction: prediction.md
